name: Deploy

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 1 * *'  # Keep it up-to-date automatically


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: theorangeone
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push containers
        uses: docker/build-push-action@v4
        with:
          platforms: linux/arm,linux/amd64,linux/arm64/v8
          push: true
          tags: |
            theorangeone/static-server:latest
            ghcr.io/realorangeone/static-server:latest
